### PR TITLE
bash: change requires to package names

### PR DESCRIPTION
**Pull request by anphel31**
###### Merge Checklist  

**All** boxes should be checked before merging the PR *(just tick any boxes which don't apply to this PR)*
- [ ] The toolchain has been rebuilt successfully (or no changes were made to it)
- [ ] The toolchain/worker package manifests are up-to-date
- [ ] Any updated packages successfully build (or no packages were changed)
- [x] Packages depending on static components modified in this PR (Golang, `*-static` subpackages, etc.) have had their `Release` tag incremented.
- [x] Package tests (%check section) have been verified with RUN_CHECK=y for existing SPEC files, or added to new SPEC files
- [x] All package sources are available
- [x] cgmanifest files are up-to-date and sorted (`./cgmanifest.json`, `./toolkit/scripts/toolchain/cgmanifest.json`, `.github/workflows/cgmanifest.json`)
- [x] LICENSE-MAP files are up-to-date (`./SPECS/LICENSES-AND-NOTICES/data/licenses.json`, `./SPECS/LICENSES-AND-NOTICES/LICENSES-MAP.md`, `./SPECS/LICENSES-AND-NOTICES/LICENSE-EXCEPTIONS.PHOTON`)
- [x] All source files have up-to-date hashes in the `*.signatures.json` files
- [x] `sudo make go-tidy-all` and `sudo make go-test-coverage` pass
- [x] Documentation has been updated to match any changes to the build system
- [ ] Ready to merge

---

###### Summary 

What does the PR accomplish, why was it needed?
Modify bash requires to use package names instead of hard-coded paths (like /bin/mv and /bin/cp). Should resolve build break in libguestfs package that was caused by a recent change in coreutils (the /bin/mv binary moved to /usr/bin/mv)

###### Change Log  

- Change bash.spec to require coreutils (for mv and cp binaries) and grep (for grep binary)

###### Does this affect the toolchain?  

**YES**

###### Test Methodology

- Pipeline build id: xxxx

### CODE REVIEW

**Review by neha170 — COMMENTED** [review]
Hi Andrew, thanks for fixing the break. I found /bin/grep in many other spec files e.g. WALinuxAgent, dracut, tcsh, zsh and resource-agents. Do you think those should be included too in the change? Similarly, /bin/mv in perl-XML-LibXML, thanks

**Review by rmhsawyer — COMMENTED** [review]
Thanks for fixing this. Looks like /bin/ln is also used in those packages and needs to be changed 
../SPECS/cracklib/cracklib.spec:17:Requires:         /bin/ln
../SPECS/cracklib/cracklib.spec:18:Requires(post):   /bin/ln
../SPECS/ca-certificates/ca-certificates.spec:73:BuildRequires:  /bin/ln

**Comment by dmcilvaney** [comment]
Moving to `/usr/bin` brings us in alignment with Fedora here: https://docs.fedoraproject.org/en-US/packaging-guidelines/#_file_and_directory_dependencies

They do say that you should NOT use directory macros here (`%{_bindir}` etc ) so that isn't a way forward.

**Comment by dmcilvaney** [comment]
I think using the path versions are useful when we have multiple packages providing the same file (busybox etc?). But it seems like we don't have multiple copies of `/bin/mv`.

File: SPECS/bash/bash.spec [hunk 1]
```diff
@@ -12,10 +12,10 @@ Source1:        bash_completion
 Patch0:         bash-5.1.patch
 BuildRequires:  readline
 Requires:       readline
-Requires(post): /bin/cp
-Requires(post): /bin/grep
-Requires(postun): /bin/grep
-Requires(postun): /bin/mv
+Requires(post): coreutils
```
Comment (PawelWMS) [inline SPECS/bash/bash.spec:15]: I'm fine with this change but file paths are used across many specs and in general should work, so we might need to think of a more future-proof solution, so that our package declare provides for directories, that are just symbolic links like `/bin` or `/lib`. An update to the steps ran after the `%install` section might do the trick. That's out of scope for this PR, though, but I was curious of your opinion. If you agree, I can add a bug for us to address this in the future.

**Review by PawelWMS — APPROVED** [review]

File: SPECS/bash/bash.spec (hunk 1 above)
Comment (dmcilvaney) [reply SPECS/bash/bash.spec:15]: The Fedora packaging guide is fine with paths, but ONLY to `/usr/bin` (among some others).  I think the big issue here is we have a mixture of `/bin` and `/usr/bin`. Taking with someone on another team who ran into this a while ago `dnf` handles these mismatches properly, and either follows the symlinks or has some other logic to figure this out. `tdnf` however does not implement t his.

**Comment by anphel31** [comment]
I'm holding off on this PR for now since the breaking change in #4255 was reverted
