### ISSUE TITLE
tuned 2.21 not working with python3.12

### ISSUE THREAD

**Issue by ankithmr** [microsoft/CBL-Mariner#10607]
tuned 2.21 service fails to start with python 3.12. It seems in Python3.12 inspect.getargspec() has been deprecated. 

```
$ rpm -iq tuned
tuned-2.21.0-1.azl3.noarch
```

**To Reproduce**
1. systemctl enable tuned

```
 systemctl status tuned
× tuned.service - Dynamic System Tuning Daemon
     Loaded: loaded (/usr/lib/systemd/system/tuned.service; enabled; preset: disabled)
    Drop-In: /usr/lib/systemd/system/service.d
             └─10-timeout-abort.conf
     Active: failed (Result: timeout) since Thu 2024-10-03 12:41:05 UTC; 7min ago
       Docs: man:tuned(8)
             man:tuned.conf(5)
             man:tuned-adm(8)
   Main PID: 99148 (code=exited, status=0/SUCCESS)
        CPU: 432ms

  File "/usr/lib/python3.12/site-packages/tuned/exports/dbus_exporter.py", line 170>
    wrapper = dbus.service.signal(self._interface_name, out_signature)(wrapper)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/dbus/decorators.py", line 329, in decorat>
    args = inspect.getargspec(func)[0]
           ^^^^^^^^^^^^^^^^^^
AttributeError: module 'inspect' has no attribute 'getargspec'. Did you mean: 'geta>
systemd[1]: tuned.service: start operation timed out. Terminating.
systemd[1]: tuned.service: Failed with result 'timeout'.
systemd[1]: Failed to start tuned.service - Dynamic System Tuning Daemon.

```

**Comment by mfrw** [comment]
Thank you for bringing this to our notice.

**Comment by zcobol** [comment]
The correct invocation is `inspect.getfullargspec()` and if you change it to `args = inspect.getfullargspec(func)[0]` in `/usr/lib/python3.12/site-packages/dbus/decorators.py` around line 330 then `systemctl start tuned` works fine.

See details at https://docs.python.org/3/library/inspect.html

**Comment by ankithmr** [comment]
I have managed to make it with by changing `inspect.getfullargspec()` to this `args = inspect.getfullargspec(func)[0]`. in /usr/lib/python3.12/site-packages/dbus/decorators.py. However, shouldn't it be fixed in the python3.12 rpm itself ? I am using the default that comes with AZL3:  `https://packages.microsoft.com/azurelinux/3.0/prod/base/x86_64/Packages/p/python3-3.12.3-2.azl3.x86_64.rpm `. I think updating `https://packages.microsoft.com/azurelinux/3.0/prod/base/x86_64/Packages/d/dbus-python-devel-1.2.16-3.azl3.x86_64.rpm` to latest version (I guess its taken from RHEL) should fix it.

**Comment by ankithmr** [comment]
Anything on this ?

**Comment by xfoukas** [comment]
Has there been any update with regards to this issue? Even with the workaround suggested above, the daemon can start, but the service does not work properly, with more python issues reported. This is what I see in the tuned logs under `/var/log/tuned/tuned.log`, once the service is started:

```
  self._call_scripts(instance._scripts, ["start"])
  File "/usr/lib/python3.12/site-packages/tuned/plugins/plugin_script.py", line 78, in _call_scripts
    if not self._safe_script_path(script):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/tuned/plugins/base.py", line 217, in _safe_script_path
    profile_paths = self._global_cfg.get_list(consts.CFG_PROFILE_DIRS, consts.CFG_DEF_PROFILE_DIRS)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'GlobalConfig' object has no attribute 'get_list'. Did you mean: 'get_int'?
```

**Comment by eric-desrochers** [comment]
ADO item #62259242 created for continuity. Closing this GH.

**Comment by eric-desrochers** [comment]
Is this still valid ? I couldn't reproduce:

```
$ rpm -qa tuned
tuned-2.21.0-2.azl3.noarch
```

```
$  systemctl status tuned
● tuned.service - Dynamic System Tuning Daemon
     Loaded: loaded (/usr/lib/systemd/system/tuned.service;
disabled; preset: disabled)
    Drop-In: /usr/lib/systemd/system/service.d
             └─10-timeout-abort.conf
     Active: active (running) since Wed 2026-05-13 18:11:16 UTC; 50s ago
       Docs: man:tuned(8)
             man:tuned.conf(5)
             man:tuned-adm(8)
   Main PID: 4792 (tuned)
      Tasks: 4 (limit: 4074)
     Memory: 17.8M (peak: 19.9M)
        CPU: 604ms
     CGroup: /system.slice/tuned.service
             └─4792 /usr/bin/python3 -Es /usr/sbin/tuned -l -P
```
